### ISSUE TITLE
Does ajc support Java8?

### ISSUE THREAD

**Issue by michaelwang** [emacs-java/auto-java-complete#9]
I am using Java8 , 
the tag file  size ( java_base.tag) up to 22M, 
When I edit java in emacs and press TAB to auto completion,
I have to wait long time to see method tips popup,
in the mean time , I watch the cpu usage up to 100%.

**Comment by jixiuf** [comment]
1. now it doe not support Java8 . 
    And I does not have so much time to support it . 
    anyone who want to contribute to this project ,welcome .
2. I suggest you ignore some useless package  when generate tag files 
   
   java  Tags "org.hello,org.world"
